// app/layout.jsx (or layout.js)
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { StoreProvider } from "./providers/storeProvider";
import SocketProvider from "./providers/socketProvider";
import { ToastContainer } from "react-toastify";
import Header from "./components/header";
import AudioUnlockButton from "./components/AudioUnlockButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SocketProvider>
          {/* <AudioUnlockButton /> */}
          <StoreProvider>{children}</StoreProvider>
        </SocketProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
